version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: boiadda
      POSTGRES_USER: boiadda
      POSTGRES_PASSWORD: boiadda_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U boiadda"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      ENVIRONMENT: production
      DATABASE_URL: postgresql://boiadda:boiadda_password@db:5432/boiadda
      SECRET_KEY: change-this-super-secret-key-in-production
      CORS_ORIGINS: http://localhost:3000,http://localhost:5173
      SEED_DEMO_DATA: false
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/healthz')"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
